<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | MoneyGrid</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: "DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
            color: #171717;
            background-color: #fafafa;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 800px;
            margin: 0 auto;
            background: #ffffff;
            padding: 40px;
            border-radius: 24px;
            box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 20px 25px -5px rgb(0 0 0 / 0.05);
            border: 1px solid #e5e5e5;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
          }
          h1 {
            font-size: 32px;
            font-weight: 700;
            margin: 0 0 8px 0;
            color: #2563eb;
          }
          .url-main {
            font-size: 16px;
            color: #737373;
            margin-bottom: 24px;
            display: block;
            text-decoration: none;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            text-align: left;
            padding: 12px;
            border-bottom: 2px solid #f0f0f0;
            color: #737373;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
          }
          td {
            padding: 16px 12px;
            border-bottom: 1px solid #f5f5f5;
            font-size: 14px;
          }
          tr:hover td {
            background-color: #f8faff;
          }
          a {
            color: #2563eb;
            text-decoration: none;
            font-weight: 500;
          }
          a:hover {
            text-decoration: underline;
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #a3a3a3;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>MoneyGrid</h1>
            <a href="https://moneygrid.vercel.app/" class="url-main">moneygrid.vercel.app</a>
            <p>This is the XML Sitemap, meant for consumption by search engines like Google or Bing.</p>
          </div>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Priority</th>
                <th>Change Freq</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <xsl:variable name="itemURL">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:variable>
                    <a href="{$itemURL}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:priority"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:lastmod"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          <div class="footer">
            Generated by MoneyGrid SEO Optimizer
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
